version: "3"
services:
  postgres:
    build:
      context: ./postgres
    container_name: postgres
    restart: always
    environment:
      POSTGRES_PASSWORD: example
    ports:
      - "5432:5432"

  redis:
    image: redis:alpine
    container_name: redis

  python:
    build:
      context: ./python
      dockerfile: Dockerfile.python
    # image: python:3.7
    container_name: python
    volumes:
      - ./python:/app
    command: /bin/sh -c "cd /app && python redis-ingest.py"
    environment:
    - REDIS_URL=redis://redis:6379/0
    depends_on:
      - redis

  server:
    image: node:dubnium
    container_name: server
    volumes:
      - ./:/app
    ports:
      - "5000:5000"
    command: bash -c "cd /app && npm run server"
    environment:
      - REDIS_URL=redis://redis:6379/0
      - DATABASE_URL=postgresql://postgres:example@postgres:5432
      - GOOGLE_APPLICATION_CREDENTIALS=/app/server/auth/google-credentials.json
    depends_on:
      - python
      - postgres

  client:
    image: node:dubnium
    container_name: client
    volumes:
      - ./:/app
    ports:
      - "3000:3000"
    command: bash -c "cd /app && npm run start"
    environment:
      - REACT_APP_SOCKET=127.0.0.1:5000
    depends_on:
      - server


